const SHOP_DATA = {
  cpu: {
    id: 1,
    title: "CPU",
    routeName: "cpu",
    items: [
      {
        id: 1,
        name: "Intel Core 2 Duo E7300",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/0ce96ac1818c47c739db32a18461ef4f.256p.jpg",
        price: 12,
        infoUrl:
          "https://pcpartpicker.com/product/wWsKHx/intel-cpu-eu80571ph0673m",
        specs: {
          "part_#": ["EU80571PH0673M"],
          manufacturer: "Intel",
          core_Count: 2,
          core_Clock: "2.66 GHz",
          tDP: "65 W",
          series: "Intel Core 2 Duo",
          microarchitecture: "Wolfdale",
          core_Family: "Wolfdale",
          integrated_Graphics: "None",
          ecc_Support: "None",
          packaging: "OEM/Tray",
          includes_CPU_cooler: "No",
          l1_Cache: ["2 x 32 kB Instruction", "2 x 32 kB Data"],
          l2_Cache: "1 x 3 MB",
          l3_Cache: "None",
          lithography: "45 nm",
          simultaneous_Multithreading: "None",
        },
      },
      {
        id: 2,
        name: "AMD Athlon II X2 220",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/11gWYQzlStL.jpg",
        price: 24.19,
        infoUrl:
          "https://pcpartpicker.com/product/CRtCmG/amd-cpu-adx220ock22gm",
        specs: {
          "part_#": ["ADX220OCK22GM"],
          manufacturer: "AMD",
          core_Count: 2,
          core_Clock: "2.8 GHz",
          tDP: "65 W",
          series: "AMD Athlon II X2",
          microarchitecture: "K10",
          core_Family: "Regor",
          socket: "AM3",
          integrated_Graphics: "None",
          ecc_Support: "None",
          packaging: "OEM/Tray",
          includes_Cpu_Cooler: "No",
          l1_Cache: ["2 x 64 kB Instruction", "2 x 64 kB Data"],
          l2_Cache: "2 x 512 kB",
          l3_Cache: "None",
          lithography: "45 nm",
          simultaneous_Multithreading: "None",
        },
      },
      {
        id: 3,
        name: "AMD 2650",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/41zx6N7xczL.jpg",
        price: 49.89,
        infoUrl:
          "https://pcpartpicker.com/product/tLvRsY/amd-cpu-sd2650jahmbox",
        "part_#": ["SD2650JAHMBOX"],
        specs: {
          manufacturer: "AMD",
          core_Count: 2,
          core_Clock: "1.45 GHz",
          tDP: "25 W",
          series: "AMD Sempron",
          microarchitecture: "Jaguar",
          core_Family: "Kabini",
          integrated_Graphics: "Radeon HD 8240",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_Cpu_Cooler: "Yes",
          l1_Cache: ["2 x 32 kB Instruction", "2 x 32 kB Data"],
          l2_Cache: "1 x 1 MB",
          l3_Cache: "None",
          lithography: "28 nm",
          simultaneous_Multithreading: "None",
        },
      },
      {
        id: 4,
        name: "Intel Core i7-930",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/51Gh-bnNLKL.jpg",
        price: 84.27,
        infoUrl: "https://pcpartpicker.com/product/qjMFf7/intel-cpu-bx80601930",
        specs: {
          "part_#": ["BX80601930"],
          manufacturer: "Intel",
          core_Count: 4,
          core_Clock: "2.8 GHz",
          tDP: "130 W",
          series: "Intel Core i7",
          microarchitecture: "Nehalem",
          core_Family: "Bloomfield",
          integrated_Graphics: "None",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_Cpu_Cooler: "Yes",
          l1_Cache: ["4 x 32 kB Instruction", "4 x 32 kB Data"],
          l2_Cache: "4 x 256 kB",
          l3_Cache: "1 x 8 MB",
          lithography: "45 nm",
          simultaneous_Multithreading: "Yes: Hyper-Threading",
        },
      },
      {
        id: 5,
        name: "Intel Core i5-3470",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/51ywEF%2BYaiL.jpg",
        price: 122.98,
        infoUrl:
          "https://pcpartpicker.com/product/PBCwrH/intel-cpu-bx80637i53470",
        specs: {
          "part_#": ["BX80637i53470"],
          manufacturer: "Intel",
          core_Count: 4,
          core_Clock: "3.2 GHz",
          tDP: "77 W",
          series: "Intel Core i5",
          microarchitecture: "Ivy Bridge",
          core_Family: "Ivy Bridge",
          integrated_Graphics: "Intel HD Graphics 2500",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_Cpu_Cooler: "Yes",
          l1_Cache: ["4 x 32 kB Instruction", "4 x 32 kB Data"],
          l2_Cache: "4 x 256 kB",
          l3_Cache: "1 x 6 MB",
          lithography: "22 nm",
          simultaneous_Multithreading: "None",
        },
      },
      {
        id: 6,
        name: "AMD Ryzen 3 3200G",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/3567a863156c083a7d4c8fcb7e0dbdac.256p.jpg",
        price: 128.99,
        infoUrl:
          "https://pcpartpicker.com/product/J8drxr/amd-ryzen-3-3200g-36-ghz-quad-core-processor-yd3200c5fhbox",
        specs: {
          "part_#": ["Ryzen 3 3200G", "YD3200C5FHBOX"],
          manufacturer: "AMD",
          core_Count: 4,
          core_Clock: "3.6 GHz",
          tDP: "65 W",
          boost_Clock: "4 GHz",
          series: "AMD Ryzen 3",
          microarchitecture: "Zen+",
          core_Family: "Picasso",
          socket: "AM4",
          integrated_Graphics: "Radeon Vega 8",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_CPU_Cooler: "Yes",
          l1_Cache: ["4 x 32 kB Instruction", "4 x 64 kB Data"],
          l2_Cache: "4 x 512 kB",
          l3_Cache: "1 x 4 MB",
          lithography: "12 nm",
          simultaneous_Multithreading: "None",
        },
      },
      {
        id: 7,
        name: "AMD Ryzen 5 1600 (12nm)",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/2447958ccca245b5827bf05929f870e6.256p.jpg",
        price: 172.99,
        infoUrl:
          "https://pcpartpicker.com/product/8HqBD3/amd-ryzen-5-1600-12nm-32-ghz-6-core-processor-yd1600bbafbox",
        specs: {
          "part_#": ["YD1600BBAFBOX"],
          manufacturer: "AMD",
          core_Count: 6,
          core_Clock: "3.2 GHz",
          boost_Clock: "3.6 GHz",
          tDP: "65 W",
          series: "AMD Ryzen 5",
          microarchitecture: "Zen+",
          core_Family: "Pinnacle Ridge",
          socket: "AM4",
          integrated_Graphics: "None",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_CPU_Cooler: "Yes",
          l1_Cache: ["6 x 64 kB Instruction", "6 x 32 kB Data"],
          l2_Cache: "6 x 512 kB",
          l3_Cache: "2 x 8 MB",
          lithography: "12 nm",
          simultaneous_Multithreading: "Yes",
        },
      },
      {
        id: 8,
        name: "AMD Ryzen 5 2600",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/55aea2dd64e2e3a3e3b1d678048d8d76.256p.jpg",
        price: 185.99,
        infoUrl:
          "https://pcpartpicker.com/product/jLF48d/amd-ryzen-5-2600-34ghz-6-core-processor-yd2600bbafbox",
        specs: {
          "part_#": ["YD2600BBAFBOX"],
          manufacturer: "AMD",
          core_Count: 6,
          core_Clock: "3.4",
          boost_Clock: "3.9 GHz",
          tDP: "65 W",
          series: "AMD Ryzen 5",
          microarchitecture: "Zen+",
          core_Family: "Pinnacle Ridge",
          socket: "AM4",
          integrated_Graphics: "None",
          maximum_Supported_Memory: "64 GB",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_CPU_Cooler: "Yes",
          l1_Cache: ["6 x 64 kB Instruction", "6 x 32 kB Data"],
          l2_cache: "6 x 512 kB",
          l3_cache: "1 x 15.99 MB",
          lithography: "12 nm",
          simultaneous_multithreading: "Yes",
        },
      },
      {
        id: 9,
        name: "AMD Ryzen 9 5950X",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/1d7073a2deda3bd22963a7e248bbe3e4.256p.jpg",
        price: 999,
        infoUrl:
          "https://pcpartpicker.com/product/Qk2bt6/amd-ryzen-9-5950x-34-ghz-16-core-processor-100-100000059wof",
        specs: {
          "part_#": ["100-100000059WOF"],
          manufacturer: "AMD",
          core_Count: 16,
          core_Clock: "3.4 GHz",
          boost_Clock: "4.9 GHz",
          tDP: "105 W",
          series: "AMD Ryzen 9",
          microarchitecture: "Zen 3",
          core_Family: "Vermeer",
          socket: "AM4",
          integrated_Graphics: "None",
          maximum_Supported_Memory: "128 GB",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_CPU_Cooler: "None",
          l1_Cache: ["16 x 32 kB Instruction", "16 x 32 kB Data"],
          l2_Cache: "16 x 512 kB",
          l3_Cache: "2 x 32 MB",
          lithography: "7 nm",
          simultaneous_multithreading: "Yes",
        },
      },
      {
        id: 10,
        name: "Intel Xeon E5-2699 V4",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/512zWhJuLmL.jpg",
        price: 1087.01,
        infoUrl:
          "https://pcpartpicker.com/product/rd98TW/intel-cpu-cm8066002022506",
        specs: {
          "part_#": ["CM8066002022506"],
          manufacturer: "Intel",
          core_Count: 22,
          core_Clock: "2.2 GHz",
          boost_Clock: "3.6 GHz",
          tDP: "145 W",
          series: "Intel Xeon E5",
          microarchitecture: "Broadwell",
          core_Family: "Broadwell-EP",
          socket: "LGA2011-3",
          integrated_Graphics: "None",
          maximum_Supported_Memory: "1536 GB",
          ecc_Support: "Yes",
          packaging: "OEM/Tray",
          includes_CPU_Cooler: "None",
          l1_Cache: ["22 x 32 kB Instruction", "22 x 32 kB Data"],
          l2_Cache: "22 x 256 kB",
          l3_Cache: "1 x 55 MB",
          lithography: "14 nm",
          simultaneous_multithreading: "Yes: Hyper-Threading",
        },
      },
      {
        id: 11,
        name: "AMD Threadripper 3960X",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/3ada9b0ee52763b884f3f76b681846ad.256p.jpg",
        price: 1399,
        infoUrl:
          "https://pcpartpicker.com/product/kNyqqs/amd-ryzen-9-3960x-38-ghz-24-core-processor-100-100000010wof",
        specs: {
          "part_#": ["100-100000010WOF"],
          manufacturer: "AMD",
          core_Count: 24,
          core_Clock: "3.8 GHz",
          boost_Clock: "4.5 GHz",
          tDP: "280 W",
          series: "AMD Threadripper",
          microarchitecture: "Zen 2",
          core_Family: "Castle Peak",
          socket: "sTRX4",
          integrated_Graphics: "None",
          maximum_Supported_Memory: "512 GB",
          ecc_Support: "Yes",
          packaging: "Boxed",
          includes_CPU_Cooler: "None",
          l1_Cache: ["24 x 32 kB Instruction", "24 x 32 kB Data"],
          l2_Cache: "24 x 512 kB",
          l3_Cache: "8 x 16 MB",
          lithography: "7 nm",
          simultaneous_multithreading: "Yes",
        },
      },
      {
        id: 12,
        name: "Intel Core i9-7900X",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/934aeb46f8ae9d26bed3d673b7c635c9.256p.jpg",
        price: 1798.95,
        infoUrl:
          "https://pcpartpicker.com/product/GmtWGX/intel-core-i9-7900x-33ghz-10-core-processor-bx80673i97900x",
        specs: {
          "part_#": ["BX80673I97900X"],
          manufacturer: "Intel",
          core_Count: 10,
          core_Clock: "3.3 GHz",
          boost_Clock: "4.5 GHz",
          tDP: "140 W",
          series: "Intel Core i9",
          microarchitecture: "Skylake",
          core_Family: "Skylake-X",
          socket: "LGA2066",
          integrated_Graphics: "None",
          maximum_Supported_Memory: "128 GB",
          ecc_Support: "None",
          packaging: "Boxed",
          includes_CPU_Cooler: "None",
          l1_cache: ["10 x 32 kB Instruction", "10 x 32 kB Data"],
          l2_cache: "10 x 1 MB",
          l3_cache: "1 x 13.75 MB",
          lithography: "14 nm",
          simultaneous_multithreading: "Yes: Hyper-Threading",
        },
      },
    ],
  },
  cpu_coolers: {
    id: 2,
    title: "CPU Coolers",
    routeName: "cpu_coolers",
    items: [
      {
        id: 13,
        name: "Cooler Master Hyper 212 EVO",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/ddea57de9797549e80d05fb3acb2e83d.med.256p.jpg",
        price: 31.99,
        infoUrl:
          "https://pcpartpicker.com/product/hmtCmG/cooler-master-cpu-cooler-rr212e20pkr2",
        specs: {
          "part_#": ["RR-212E-20PK-R2", "RR-212E-16PK-R1"],
          manufacturer: "Cooler Master",
          fan_RPM: "600 - 2000 RPM",
          noise_Level: "9 - 36 dB",
          height: "159 mm",
          bearing: "Sleeve",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "LGA775",
          ],
          water_Cooled: "No",
          fanless: "No",
        },
      },
      {
        id: 14,
        name: "NZXT Kraken X53",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/098f91f23535f45875611413e7b892d6.256p.jpg",
        price: 129.99,
        infoUrl:
          "https://pcpartpicker.com/product/PVfFf7/nzxt-kraken-x53-7311-cfm-liquid-cpu-cooler-rl-krx53-01",
        specs: {
          "part_#": ["RL-KRX53-01"],
          fan_RPM: "500 - 2000 RPM",
          noise_Level: "21 - 36 dB",
          cpu_Socket: [
            "AM4",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "sTR4",
            "sTRX4",
          ],
          water_Cooled: "Yes - 240 mm",
          fanless: "No",
        },
      },
      {
        id: 15,
        name: "Corsair iCUE H100i ELITE CAPELLIX",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/3e80087537051bd56fa7650e7d61516d.256p.jpg",
        price: 137.99,
        infoUrl:
          "https://pcpartpicker.com/product/VDWBD3/corsair-icue-h100i-elite-capellix-75-cfm-liquid-cpu-cooler-cw-9060046-ww",
        specs: {
          "part_#": ["CW-9060046-WW"],
          manufacturer: "Corsair",
          fan_RPM: "2400 RPM",
          noise_Level: "10 - 37 dB",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "sTR4",
            "sTRX4",
          ],
          water_Cooled: "Yes - 240 mm",
          fanless: "No",
        },
      },
      {
        id: 16,
        name: "be quiet! Dark Rock Pro 4",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/8ab57dc3c0eb346c72ef7a2405e31227.256p.jpg",
        price: 79.98,
        infoUrl:
          "https://pcpartpicker.com/product/F3gzK8/be-quiet-dark-rock-pro-4-505-cfm-cpu-cooler-bk022",
        specs: {
          "part_#": ["BK022"],
          manufacturer: "be quiet!",
          fan_RPM: "1500 RPM",
          noise_Level: "12.8 - 24.3 dB",
          height: "162.8 mm",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
          ],
          water_Cooled: "No",
          fanless: "No",
        },
      },
      {
        id: 17,
        name: "Asus ROG STRIX LC 360 RGB White",
        imageUrl: "https://m.media-amazon.com/images/I/41KkBKEGZ7L.jpg",
        price: 251.99,
        infoUrl:
          "https://pcpartpicker.com/product/7RXYcf/asus-rog-strix-lc-360-rgb-white-8095-cfm-liquid-cpu-cooler-rog-strix-lc-360-rgb-white",
        specs: {
          "part_#": ["ROG STRIX LC 360 RGB White"],
          manufacturer: "Asus",
          fan_RPM: "800 - 2500 RPM",
          noise_Level: "37.6 dB",
          cpu_Socket: [
            "AM4",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "sTR4",
            "sTRX4",
          ],
          water_Cooled: "Yes - 360 mm",
          fanless: "No",
        },
      },
      {
        id: 18,
        name: "Deepcool GAMMAXX 400 Blue",
        imageUrl:
          "https://images-fe.ssl-images-amazon.com/images/I/61ejeleLpqL.jpg",
        price: 24.99,
        infoUrl:
          "https://pcpartpicker.com/product/w3c48d/deepcool-gammaxx-400-blue-7434-cfm-cpu-cooler-deepcool-gammaxx-400-blue",
        specs: {
          "part_#": ["DEEPCOOL GAMMAXX 400 Blue"],
          manufacturer: "Deepcool",
          fan_RPM: "900 - 1500 RPM",
          noise_Level: "17.8 - 30 dB",
          height: "154.5 mm",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "LGA775",
          ],
          water_Cooled: "No",
          fanless: "No",
        },
      },
      {
        id: 19,
        name: "Cooler Master Hyper 212 LED",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/51cGorhBx9L.jpg",
        price: 34.99,
        infoUrl:
          "https://pcpartpicker.com/product/YdJkcf/cooler-master-hyper-212-led-663-cfm-rifle-bearing-cpu-cooler-rr-212l-16pr-r1",
        specs: {
          "part_#": ["RR-212L-16PR-R1"],
          manufacturer: "Cooler Master",
          fan_RPM: "600 - 1600 RPM",
          noise_Level: "9 - 31 dB",
          height: "160 mm",
          bearing: "Rifle",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "LGA775",
          ],
          water_Cooled: "No",
          fanless: "No",
        },
      },
      {
        id: 20,
        name: "Cooler Master MasterLiquid ML120R RGB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/3deec0e55023fbed6eef4a89cb89713c.256p.jpg",
        price: 84.99,
        infoUrl:
          "https://pcpartpicker.com/product/7tQG3C/cooler-master-masterliquid-ml120r-rgb-667-cfm-liquid-cpu-cooler-mlx-d12m-a20pc-r1",
        specs: {
          "part_#": ["MLX-D12M-A20PC-R1"],
          manufacturer: "Cooler Master",
          fan_RPM: "650 - 2000 RPM",
          noise_Level: "6 - 30 dB",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "LGA775",
          ],
          water_Cooled: "Yes - 120 mm",
          fanless: "No",
        },
      },
      {
        id: 21,
        name: "SilenX EFZ-100HA2",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/51oG3SuDs4L.jpg",
        price: 14.95,
        infoUrl:
          "https://pcpartpicker.com/product/yFV48d/silenx-cpu-cooler-efz100ha2",
        specs: {
          "part_#": ["EFZ-100HA2"],
          manufacturer: "SilenX",
          fan_RPM: "2400",
          noise_Level: "8 - 24 dB",
          height: "56 mm",
          bearing: "Fluid Dynamic",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA775",
          ],
          water_Cooled: "No",
          fanless: "No",
        },
      },
      {
        id: 22,
        name: "Thermaltake UX200 ARGB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/1d87a6d070c19217787815a75d76c8bd.256p.jpg",
        price: 39.99,
        infoUrl:
          "https://pcpartpicker.com/product/yLsnTW/thermaltake-ux200-argb-4334-cfm-cpu-cooler-cl-p065-al12sw-a",
        specs: {
          "part_#": ["CL-P065-AL12SW-A"],
          manufacturer: "Thermaltake",
          fan_RPM: "300 - 1500 RPM",
          noise_Level: "26.33 dB",
          height: "153.5 mm",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA775",
          ],
          water_Cooled: "No",
          fanless: "No",
        },
      },
      {
        id: 23,
        name: "Cougar Helor 240",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/512f831f7b5f0cc7bc41aa0b3a1abc73.256p.jpg",
        price: 109.9,
        infoUrl:
          "https://pcpartpicker.com/product/kvMwrH/cougar-helor-240-784-cfm-liquid-cpu-cooler-rl-hlr240-v1",
        specs: {
          "part_#": ["RL-HLR240-V1", "35CCL24.0001"],
          manufacturer: "Cougar",
          fan_RPM: "600 - 1800 RPM",
          noise_Level: "37.1 dB",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "LGA775",
          ],
          water_Cooled: "Yes - 240 mm",
          fanless: "No",
        },
      },
      {
        id: 24,
        name: "Alphacool Eisbaer 360",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/41Fq37cbABL.jpg",
        price: 179.95,
        infoUrl:
          "https://pcpartpicker.com/product/fyJkcf/alphacool-eisbaer-360-6385-cfm-liquid-cpu-cooler-11286",
        specs: {
          "part_#": ["11286", "1012138"],
          manufacturer: "Alphacool",
          fan_RPM: "550 - 1700 RPM",
          noise_Level: "29 dB",
          cpu_Socket: [
            "AM2",
            "AM2+",
            "AM3",
            "AM3+",
            "AM4",
            "FM1",
            "FM2",
            "FM2+",
            "G34",
            "LGA1150",
            "LGA1151",
            "LGA1155",
            "LGA1156",
            "LGA1200",
            "LGA1366",
            "LGA2011",
            "LGA2011-3",
            "LGA2066",
            "LGA3647",
            "sTR4",
            "sTRX4",
          ],
          water_Cooled: "Yes - 360 mm",
          fanless: "No",
        },
      },
    ],
  },
  motherboards: {
    id: 3,
    title: "Motherboard",
    routeName: "motherboards",
    items: [
      {
        id: 25,
        name: "Asus TUF GAMING X570-PLUS (WI-FI)",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/8d7d0435e8a2af93b5d91a1a5dccd476.256p.jpg",
        price: 192.99,
        infoUrl:
          "https://pcpartpicker.com/product/dmGnTW/asus-tuf-gaming-x570-plus-wi-fi-atx-am4-motherboard-tuf-gaming-x570-plus-wi-fi",
        specs: {
          "part_#": [
            "TUF GAMING X570-PLUS (WI-FI)",
            "90MB1170-MVAAY0",
            "90MB1170-M0EAY0",
          ],
          manufacturer: "Asus",
          socket: "AM4",
          form_Factor: "ATX",
          chipset: "AMD X570",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3300",
            "DDR4-3400",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4266",
            "DDR4-4400",
          ],
          crossFire: ["CrossFire Capable"],
          "pCI-E_x16_Slots": "2",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "2",
          pCI_Slots: "0",
          "m.2_Slots": [
            "2242/2260/2280/22110 M-key",
            "2242/2260/2280/22110 M-key",
          ],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s"],
          "sATA_6_Gb/s": "8",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "Wi-Fi 5",
          rAID_Support: "Yes",
        },
      },
      {
        id: 26,
        name: "ASRock B450M PRO4",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/8f8baff091bfd5ef531c7ddb1a602ca4.256p.jpg",
        price: 79.73,
        infoUrl:
          "https://pcpartpicker.com/product/dQgzK8/asrock-b450m-pro4-micro-atx-am4-motherboard-b450m-pro4",
        specs: {
          "part_#": ["B450M PRO4", "90-MXB8F0-A0UAYZ"],
          manufacturer: "ASRock",
          socket: "AM4",
          form_Factor: "Micro ATX",
          chipset: "AMD B450",
          memory_Max: "64 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2933",
            "DDR4-3200",
          ],
          crossFire: ["CrossFire Capable"],
          "pCI-E_x16_Slots": "2",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "1",
          pCI_Slots: "0",
          "m.2_Slots": ["2242/2260/2280 M-key", "2230/2242/2260/2280 M-key"],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s"],
          "sATA_6_Gb/s": "4",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "0",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "None",
          rAID_Support: "Yes",
        },
      },
      {
        id: 27,
        name: "Asus ROG Strix X570-E Gaming",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/8edda8b2608b4fe4e5c3777f9e6df4fd.256p.jpg",
        price: 409.73,
        infoUrl:
          "https://pcpartpicker.com/product/CLkgXL/asus-rog-strix-x570-e-gaming-atx-am4-motherboard-rog-strix-x570-e-gaming",
        specs: {
          "part_#": ["ROG Strix X570-E Gaming", "90MB1150-M0EAY0"],
          manufacturer: "Asus",
          socket: "AM4",
          form_Factor: "ATX",
          chipset: "AMD X570",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-2933",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3400",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3733",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4266",
            "DDR4-4400",
          ],
          crossFire: ["CrossFire Capable", "2-Way SLI Capable"],
          "pCI-E_x16_Slots": "3",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "2",
          pCI_Slots: "0",
          "m.2_Slots": [
            "2242/2260/2280/22110 M-key",
            "2242/2260/2280/22110 M-key",
          ],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s", "1 x 2.5 Gbit/s"],
          "sATA_6_Gb/s": "8",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "1",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "Wi-Fi 6",
          rAID_Support: "Yes",
        },
      },
      {
        id: 28,
        name: "MSI Z390-A PRO",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/65d2e2e1dd6c41fe051500c6d88ffe0c.256p.jpg",
        price: 126.89,
        infoUrl:
          "https://pcpartpicker.com/product/qpL48d/msi-z390-a-pro-atx-lga1151-motherboard-z390-a-pro",
        specs: {
          "part_#": ["Z390-A PRO", "7B98-001R", "911-7B98-001"],
          socket: "LGA1151",
          form_Factor: "ATX",
          chipset: "Intel Z390",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3300",
            "DDR4-3333",
            "DDR4-3400",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3733",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4200",
            "DDR4-4266",
            "DDR4-4400",
          ],
          crossFire: ["CrossFire Capable"],
          "pCI-E_x16_Slots": "2",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "4",
          pCI_Slots: "0",
          "m.2_Slots": ["2242/2260/2280/22110 M-key", "2230 E-key"],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s"],
          "sATA_6_Gb/s": "6",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "2",
          "uSB_3.2_Gen_2_Headers": "0",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "None",
          rAID_Support: "Yes",
        },
      },
      {
        id: 29,
        name: "MSI MPG B550 GAMING EDGE WIFI",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/e1677ccd8b20b24c91fd17885a1b8b8a.256p.jpg",
        price: 179.98,
        infoUrl:
          "https://pcpartpicker.com/product/2f4BD3/msi-mpg-b550-gaming-edge-wifi-atx-am4-motherboard-mpg-b550-gaming-edge-wifi",
        specs: {
          "part_#": ["MPG B550 GAMING EDGE WIFI", "7C91-008R"],
          manufacturer: "MSI",
          socket: "AM4",
          form_Factor: "ATX",
          chipset: "AMD B550",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-1866",
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-2933",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3733",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4266",
            "DDR4-4400",
            "DDR4-4533",
            "DDR4-4600",
            "DDR4-4866",
            "DDR4-5000",
          ],
          crossFire: ["CrossFire Capable"],
          "pCI-E_x16_Slots": "2",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "2",
          pCI_Slots: "0",
          "m.2_Slots": [
            "2242/2260/2280/22110 M-key",
            "2242/2260/2280 M-key",
            "2230 E-key",
          ],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 2.5 Gbit/s"],
          "sATA_6_Gb/s": "6",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "1",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "Wi-Fi 6",
          rAID_Support: "Yes",
        },
      },
      {
        id: 30,
        name: "Asus ROG Crosshair VIII Hero (WI-FI)",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/9b0c678ccf7522e6ad454d3976a2e174.256p.jpg",
        price: 584.64,
        infoUrl:
          "https://pcpartpicker.com/product/GcfFf7/asus-rog-crosshair-viii-hero-wi-fi-atx-am4-motherboard-rog-crosshair-viii-hero-wi-fi",
        specs: {
          "part_#": [
            "ROG Crosshair VIII Hero (WI-FI)",
            "CROSSHAIR VIII HERO WI-FI",
            "90MB10T0-M0EAY0",
          ],
          manufacturer: "Asus",
          socket: "AM4",
          form_Factor: "ATX",
          chipset: "AMD X570",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-2933",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3733",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4266",
            "DDR4-4400",
            "DDR4-4533",
            "DDR4-4600",
          ],
          crossFire: ["CrossFire Capable", "2-Way SLI Capable"],
          "pCI-E_x16_Slots": "3",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "1",
          pCI_Slots: "0",
          "m.2_Slots": ["2242/2260/2280 M-key", "2242/2260/2280/22110 M-key"],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s", "1 x 2.5 Gbit/s"],
          "sATA_6_Gb/s": "8",
          onboard_Video: "No",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "1",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "Wi-Fi 6",
          rAID_Support: "Yes",
        },
      },
      {
        id: 31,
        name: "Asus ROG STRIX B550-E GAMING",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/dab44f4f8369d56dbaa568de8a99700b.256p.jpg",
        price: 252.99,
        infoUrl:
          "https://pcpartpicker.com/product/PDyqqs/asus-rog-strix-b550-e-gaming-atx-am4-motherboard-rog-strix-b550-e-gaming",
        specs: {
          "part_#": [
            "ROG STRIX B550-E GAMING",
            "STRIX B550-E GAMING",
            "90MB1470-M0EAY0",
          ],
          manufacturer: "Asus",
          socket: "AM4",
          form_Factor: "ATX",
          chipset: "AMD B550",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4400",
          ],
          crossFire: ["CrossFire Capable", "2-Way SLI Capable"],
          "pCI-E_x16_Slots": "3",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "2",
          pCI_Slots: "0",
          "m.2_Slots": [
            "2242/2260/2280/22110 M-key",
            "2242/2260/2280/22110 M-key",
          ],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 2.5 Gbit/s"],
          "sATA_6_Gb/s": "6",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "1",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "Wi-Fi 6",
          rAID_Support: "Yes",
        },
      },
      {
        id: 32,
        name: "MSI B450 GAMING PRO CARBON MAX WIFI",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/1c29c33ad7631dd0359bd93b0a7a447e.256p.jpg",
        price: 139.44,
        infoUrl:
          "https://pcpartpicker.com/product/mcjNnQ/msi-b450-gaming-pro-carbon-max-wifi-atx-am4-motherboard-b450-gaming-pro-carbon-max-wifi",
        specs: {
          "part_#": ["B450 GAMING PRO CARBON MAX WIFI"],
          manufacturer: "MSI",
          socket: "AM4",
          form_Factor: "ATX",
          chipset: "AMD B450",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-2933",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3733",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
          ],
          crossFire: ["CrossFire Capable"],
          "pCI-E_x16_Slots": "2",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "3",
          pCI_Slots: "0",
          "m.2_Slots": ["2242/2260/2280/22110 M-key", "2242/2260/2280 M-key"],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s"],
          "sATA_6_Gb/s": "4",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "0",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "Wi-Fi 5",
          rAID_Support: "Yes",
        },
      },
      {
        id: 33,
        name: "Asus TUF Gaming Z590-PLUS WIFI",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/1796254752a632d703fb5659e1647668.256p.jpg",
        price: 239.99,
        infoUrl:
          "https://pcpartpicker.com/product/hD8bt6/asus-tuf-gaming-z590-plus-wifi-atx-lga1200-motherboard-tuf-gaming-z590-plus-wifi",
        specs: {
          "part_#": ["TUF Gaming Z590-PLUS WIFI", "90MB16C0-M0EAY0"],
          manufacturer: "Asus",
          socket: "LGA1200",
          form_Factor: "ATX",
          chipset: "Intel Z590",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-2933",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3333",
            "DDR4-3400",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3733",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4266",
            "DDR4-4400",
            "DDR4-4500",
            "DDR4-4600",
            "DDR4-4700",
            "DDR4-4800",
            "DDR4-5000",
          ],
          "pCI-E_x16_Slots": "2",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "2",
          pCI_Slots: "0",
          "m.2_Slots": [
            "2242/2260/2280/22110 M-key (Intel Rocket Lake-based CPUs only)",
            "2242/2260/2280/22110 M-key",
            "2242/2260/2280 M-key",
          ],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 2.5 Gbit/s"],
          "sATA_6_Gb/s": "6",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "1",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "Wi-Fi 6",
          rAID_Support: "Yes",
        },
      },
      {
        id: 34,
        name: "Asus ROG ZENITH II EXTREME ALPHA",
        imageUrl: "https://m.media-amazon.com/images/I/41CIKTk-vOL.jpg",
        price: 870.99,
        infoUrl:
          "https://pcpartpicker.com/product/zcyqqs/asus-rog-zenith-ii-extreme-alpha-eatx-strx4-motherboard-rog-zenith-ii-extreme-alpha",
        specs: {
          "part_#": [
            "ROG ZENITH II EXTREME ALPHA",
            "ZENITH II EXTREME ALPHA",
            "90MB14K0-M0EAY0",
          ],
          manufacturer: "Asus",
          socket: "sTRX4",
          form_Factor: "EATX",
          chipset: "AMD TRX40",
          memory_Max: "256 GB",
          memory_Type: "DDR4",
          memory_Slots: "8",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-3400",
            "DDR4-3733",
            "DDR4-3800",
            "DDR4-4133",
            "DDR4-4266",
            "DDR4-4333",
            "DDR4-4400",
            "DDR4-4600",
          ],
          crossFire: [
            "CrossFire Capable",
            "2-Way SLI Capable",
            "3-Way SLI Capable",
          ],
          "pCI-E_x16_Slots": "4",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "0",
          pCI_Slots: "0",
          "m.2_Slots": [
            "2242/2260/2280 M-key",
            "2242/2260/2280 M-key",
            "2242/2260/2280 M-key",
            "2242/2260/2280/22110 M-key",
            "2242/2260/2280/22110 M-key",
          ],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s", "1 x 10 Gbit/s"],
          "sATA_6_Gb/s": "8",
          onboard_Video: "No",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "2",
          "uSB_3.2_Gen_2_Headers": "2",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "Yes",
          wireless_Networking: "Wi-Fi 6",
          rAID_Support: "Yes",
        },
      },
      {
        id: 35,
        name: "Gigabyte Z490 VISION G",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/3a190c962f8bedfd2ae4c99facbb67bc.256p.jpg",
        price: 269.99,
        infoUrl:
          "https://pcpartpicker.com/product/qRhmP6/gigabyte-z490-vision-g-atx-lga1200-motherboard-z490-vision-g",
        specs: {
          "part_#": ["Z490 VISION G", "GAZ49VSG-00-G"],
          manufacturer: "Gigabyte",
          socket: "LGA1200",
          form_Factor: "ATX",
          chipset: "Intel Z490",
          memory_Max: "128 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-2933",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3300",
            "DDR4-3333",
            "DDR4-3400",
            "DDR4-3466",
            "DDR4-3600",
            "DDR4-3666",
            "DDR4-3733",
            "DDR4-3800",
            "DDR4-3866",
            "DDR4-4000",
            "DDR4-4133",
            "DDR4-4266",
            "DDR4-4300",
            "DDR4-4400",
            "DDR4-4500",
            "DDR4-4600",
            "DDR4-4700",
            "DDR4-4800",
            "DDR4-5000",
          ],
          crossFire: ["CrossFire Capable", "2-Way SLI Capable"],
          "pCI-E_x16_Slots": "3",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "2",
          pCI_Slots: "0",
          "m.2_Slots": [
            "2280 M-key (Intel Rocket Lake-based CPUs only)",
            "2260/2280/22110 M-key",
            "2260/2280 M-key",
          ],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 2.5 Gbit/s"],
          "sATA_6_Gb/s": "6",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "1",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "None",
          rAID_Support: "Yes",
        },
      },
      {
        id: 36,
        name: "MSI B450 TOMAHAWK",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/8ba566ff15c0bdf7435a68cc0e5152fa.256p.jpg",
        price: 139.0,
        infoUrl:
          "https://pcpartpicker.com/product/Hy97YJ/msi-b450-tomahawk-atx-am4-motherboard-b450-tomahawk",
        specs: {
          "part_#": ["B450 TOMAHAWK", "7C02-002R"],
          manufacturer: "MSI",
          socket: "AM4",
          form_Factor: "ATX",
          chipset: "AMD B450",
          memory_Max: "64 GB",
          memory_Type: "DDR4",
          memory_Slots: "4",
          memory_Speed: [
            "DDR4-1866",
            "DDR4-2133",
            "DDR4-2400",
            "DDR4-2666",
            "DDR4-2800",
            "DDR4-2933",
            "DDR4-3000",
            "DDR4-3200",
            "DDR4-3466",
          ],
          crossFire: ["CrossFire Capable"],
          "pCI-E_x16_Slots": "2",
          "pCI-E_x8_Slots": "0",
          "pCI-E_x4_Slots": "0",
          "pCI-E_x1_Slots": "3",
          pCI_Slots: "0",
          "m.2_Slots": ["2242/2260/2280/22110 M-key"],
          mSATA_Slots: "0",
          onboard_Ethernet: ["1 x 1 Gbit/s"],
          "sATA_6_Gb/s": "6",
          onboard_Video: "Depends on CPU",
          "uSB_2.0_Headers": "2",
          "uSB_3.2_Gen_1_Headers": "1",
          "uSB_3.2_Gen_2_Headers": "0",
          "uSB_3.2_Gen_2x2_Headers": "0",
          supports_ECC: "No",
          wireless_Networking: "None",
          rAID_Support: "Yes",
        },
      },
    ],
  },
  rams: {
    id: 4,
    title: "RAM",
    routeName: "rams",
    items: [
      {
        id: 37,
        name: "Corsair Vengeance LPX 16 GB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/835ab3efad1be13bbe53beef3e3c6f96.256p.jpg",
        price: 92.99,
        infoUrl:
          "https://pcpartpicker.com/product/p6RFf7/corsair-memory-cmk16gx4m2b3200c16",
        specs: {
          "part_#": ["CMK16GX4M2B3200C16"],
          manufacturer: "Corsair",
          form_Factor: "288-pin DIMM",
          modules: "2 x 8GB",
          "price/GB": "$5.749",
          first_Word_Latency: "10 ns",
          cAS_Latency: "16",
          voltage: "1.35 V",
          timing: "16-18-18-36",
          eCC: "Non-ECC/Unbuffered",
          heat_Spreader: "Yes",
        },
      },
      {
        id: 38,
        name: "Corsair Vengeance RGB Pro 16 GB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/58ab1663c77627cbf3effd27df57aa92.256p.jpg",
        price: 104.99,
        infoUrl:
          "https://pcpartpicker.com/product/vfDJ7P/corsair-vengeance-rgb-pro-16gb-2-x-8gb-ddr4-3200-memory-cmw16gx4m2c3200c16w",
        specs: {
          "part_#": ["CMW16GX4M2C3200C16W"],
          manufacturer: "Corsair",
          form_Factor: "288-pin DIMM",
          modules: "2 x 8GB",
          "price/GB": "$7.437",
          first_Word_Latency: "10 ns",
          cAS_Latency: "16",
          voltage: "1.35 V",
          timing: "16-18-18-36",
          eCC: "Non-ECC/Unbuffered",
          heat_Spreader: "Yes",
        },
      },
      {
        id: 39,
        name: "Corsair Vengeance RGB Pro 16 GB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/2acf8a36c3350a47689e36ee924c80f7.256p.jpg",
        price: 109.99,
        infoUrl:
          "https://pcpartpicker.com/product/XWGnTW/corsair-vengeance-rgb-pro-16-gb-2-x-8-gb-ddr4-3600-memory-cmw16gx4m2d3600c18",
        specs: {
          "part_#": ["CMW16GX4M2D3600C18"],
          manufacturer: "Corsair",
          form_Factor: "288-pin DIMM",
          modules: "2 x 8GB",
          "price/GB": "$7.637",
          first_Word_Latency: "10 ns",
          cAS_Latency: "18",
          voltage: "1.35 V",
          timing: "16-22-22-42",
          eCC: "Non-ECC/Unbuffered",
          heat_Spreader: "Yes",
        },
      },
      {
        id: 40,
        name: "G.Skill Trident Z RGB 32 GB",
        imageUrl: "https://m.media-amazon.com/images/I/419N-fz9syL.jpg",
        price: 219.99,
        infoUrl:
          "https://pcpartpicker.com/product/jxH8TW/gskill-trident-z-rgb-32-gb-2-x-16-gb-ddr4-3600-memory-f4-3600c16d-32gtzrc",
      },
      {
        id: 41,
        name: "G.Skill Trident Z Neo 16 GB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/d62078e82b57dca6362b1485f39e1064.256p.jpg",
        price: 139.99,
        infoUrl:
          "https://pcpartpicker.com/product/JgLwrH/gskill-trident-z-neo-16-gb-2-x-8-gb-ddr4-3600-cl16-memory-f4-3600c16d-16gtznc",
        specs: {
          "part_#": ["F4-3600C16D-32GTZRC"],
          manufacturer: "G.Skill",
          form_Factor: "288-pin DIMM",
          modules: "2 x 16GB",
          "price/GB": "$6.875",
          first_Word_Latency: "8.889 ns",
          cAS_Latency: "16",
          voltage: "1.35 V",
          timing: "16-19-19-39",
          eCC: "Non-ECC/Unbuffered",
          heat_Spreader: "Yes",
        },
      },
      {
        id: 42,
        name: "Patriot Viper Steel 16 GB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/a6d150a1a9e9ad94874551eee42573e4.256p.jpg",
        price: 97.99,
        infoUrl:
          "https://pcpartpicker.com/product/mCHRsY/patriot-viper-steel-16-gb-2-x-8-gb-ddr4-3200-cl16-memory-pvs416g320c6k",
        specs: {
          "part_#": ["PVS416G320C6K"],
          manufacturer: "Patriot",
          form_Factor: "288-pin DIMM",
          modules: "2 x 8GB",
          "price/GB": "$5.812",
          first_Word_Latency: "10 ns",
          cAS_Latency: "16",
          voltage: "1.35 V",
          timing: "16-18-18-36",
          eCC: "Non-ECC/Unbuffered",
          heat_Spreader: "Yes",
        },
      },
      {
        id: 43,
        name: "ADATA XPG SPECTRIX D60G 16 GB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/a881e3433b353661a219670b7aa8fc1d.256p.jpg",
        price: 104.98,
        infoUrl:
          "https://pcpartpicker.com/product/Hsxbt6/adata-xpg-spectrix-d60g-16-gb-2-x-8-gb-ddr4-3200-memory-ax4u320038g16a-dt60",
        specs: {
          "part_#": ["AX4U320038G16A-DT60"],
          manufacturer: "ADATA",
          form_Factor: "288-pin DIMM",
          modules: "2 x 8GB",
          "price/GB": "$6.062",
          first_Word_Latency: "10 ns",
          cAS_Latency: "16",
          voltage: "1.35 V",
          eCC: "Non-ECC/Unbuffered",
          heat_Spreader: "Yes",
        },
      },
      {
        id: 44,
        name: "Kingston HyperX Fury 16 GB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/f1ffc4c40a82b7b15bbb8bdb73c8157f.256p.jpg",
        price: 89.99,
        infoUrl:
          "https://pcpartpicker.com/product/7YkgXL/kingston-hyperx-fury-16-gb-2-x-8-gb-ddr4-2666-cl16-memory-hx426c16fb3k216",
        specs: {
          "part_#": ["HX426C16FB3K2/16"],
          manufacturer: "Kingston",
          form_Factor: "288-pin DIMM",
          modules: "2 x 8GB",
          "price/GB": "$5.624",
          first_Word_Latency: "12.003 ns",
          cAS_Latency: "16",
          voltage: "1.2 V",
          eCC: "Non-ECC/Unbuffered",
          heat_Spreader: "Yes",
        },
      },
    ],
  },
  storages: {
    id: 5,
    title: "Storage",
    routeName: "storages",
    items: [
      {
        id: 45,
        name: "Seagate Barracuda Compute",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/c7b5b7dacbecdcdd0e073b761193eef6.256p.jpg",
        price: 52.99,
        infoUrl:
          "https://pcpartpicker.com/product/mwrYcf/seagate-barracuda-computer-2-tb-35-7200rpm-internal-hard-drive-st2000dm008",
        specs: {
          "part_#": ["ST2000DM008"],
          manufacturer: "Seagate",
          capacity: "2 TB",
          "price/GB": "$0.028",
          type: "7200 RPM",
          cache: "256 MB",
          form_Factor: '3.5"',
          interface: "SATA 6 Gb/s",
          nVME: "No",
        },
      },
      {
        id: 46,
        name: "Samsung 970 Evo",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/09a31f32abb3daaf5ed9b849bd60e675.256p.jpg",
        price: 345.2,
        infoUrl:
          "https://pcpartpicker.com/product/JLdxFT/samsung-970-evo-10tb-m2-2280-solid-state-drive-mz-v7e1t0baw",
        specs: {
          "part_#": ["MZ-V7E1T0BW", "MZ-V7E1T0B/AM"],
          manufacturer: "Samsung",
          capacity: "1 TB",
          "price/GB": "$0.160",
          type: "SSD",
          cache: "1024 MB",
          form_Factor: "M.2-2280",
          interface: "M.2 (M)",
          nVME: "Yes",
        },
      },
      {
        id: 47,
        name: "Samsung 860 Evo",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/41qR7C253KL.jpg",
        price: 109.99,
        infoUrl:
          "https://pcpartpicker.com/product/yzfhP6/samsung-860-evo-1tb-25-solid-state-drive-mz-76e1t0bam",
        specs: {
          "part_#": ["MZ-76E1T0B/AM", "MZ-76E1T0B/EU"],
          manufacturer: "Samsung",
          capacity: "1 TB",
          "price/GB": "$0.110",
          type: "SSD",
          cache: "1024 MB",
          form_Factor: '2.5"',
          interface: "SATA 6 Gb/s",
          nVME: "No",
        },
      },
      {
        id: 48,
        name: "Western Digital Caviar Blue",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/51fbLQLVJFL.jpg",
        price: 44.99,
        infoUrl:
          "https://pcpartpicker.com/product/MwW9TW/western-digital-internal-hard-drive-wd10ezex",
        specs: {
          "part_#": ["WD10EZEX"],
          manufacturer: "Western Digital",
          capacity: "1 TB",
          "price/GB": "$0.042",
          type: "7200 RPM",
          cache: "64 MB",
          form_Factor: '3.5"',
          interface: "SATA 6 Gb/s",
          nVME: "No",
        },
      },
      {
        id: 49,
        name: "Samsung 980 Pro",
        imageUrl: "https://m.media-amazon.com/images/I/3103WN6Es-L.jpg",
        price: 199.99,
        infoUrl:
          "https://pcpartpicker.com/product/DDWBD3/samsung-980-pro-1-tb-m2-2280-nvme-solid-state-drive-mz-v8p1t0bam",
        specs: {
          "part_#": ["MZ-V8P1T0B/AM", "MZ-V8P1T0BW"],
          manufacturer: "Samsung",
          capacity: "1 TB",
          "price/GB": "$0.197",
          type: "SSD",
          cache: "1024 MB",
          form_Factor: "M.2-2280",
          interface: "M.2 (M)",
          nVME: "Yes",
        },
      },
      {
        id: 50,
        name: "Western Digital Blue SN550",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/73be90b182cdb68fe899775fb8fa56ed.256p.jpg",
        price: 59.99,
        infoUrl:
          "https://pcpartpicker.com/product/zFK2FT/western-digital-blue-sn550-500-gb-m2-2280-nvme-solid-state-drive-wds500g2b0c",
        specs: {
          "part_#": ["WDS500G2B0C"],
          manufacturer: "Western Digital",
          capacity: "500 GB",
          "price/GB": "$0.120",
          type: "SSD",
          form_Factor: "M.2-2280",
          interface: "M.2 (M)",
          nVME: "Yes",
        },
      },
      {
        id: 51,
        name: "Western Digital SN750",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/0e711f3edb98f9680cc528271201d8d2.256p.jpg",
        price: 144.99,
        infoUrl:
          "https://pcpartpicker.com/product/QQrmP6/western-digital-sn750-1-tb-m2-2280-solid-state-drive-wds100t3x0c",
        specs: {
          "part_#": ["WDS100T3X0C", "WDS100T3X0C-00SJG0"],
          manufacturer: "Western Digital",
          capacity: "1 TB",
          "price/GB": "$0.130",
          type: "SSD",
          form_Factor: "M.2-2280",
          interface: "M.2 (M)",
          nVME: "Yes",
        },
      },
      {
        id: 52,
        name: "Crucial P2",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/50d7356e9199580f1c35e7b8f01232ab.256p.jpg",
        price: 57.99,
        infoUrl:
          "https://pcpartpicker.com/product/G9XYcf/crucial-p2-500-gb-m2-2280-nvme-solid-state-drive-ct500p2ssd8",
        specs: {
          "part_#": ["CT500P2SSD8"],
          manufacturer: "Crucial",
          capacity: "500 GB",
          "price/GB": "$0.106",
          type: "SSD",
          form_Factor: "M.2-2280",
          interface: "M.2 (M)",
          nVME: "Yes",
        },
      },
      {
        id: 53,
        name: "Sabrent Rocket Q",
        imageUrl: "https://m.media-amazon.com/images/I/41bVN1EMxFL.jpg",
        price: 1299.99,
        infoUrl:
          "https://pcpartpicker.com/product/qdPgXL/sabrent-rocket-q-8-tb-m2-2280-nvme-solid-state-drive-sb-rktq-8tb",
        specs: {
          "part_#": ["SB-RKTQ-8TB"],
          manufacturer: "Sabrent",
          capacity: "8 TB",
          "price/GB": "$0.175",
          type: "SSD",
          form_Factor: "M.2-2280",
          interface: "M.2 (M)",
          nVME: "Yes",
        },
      },
      {
        id: 54,
        name: "Western Digital Gold",
        imageUrl: "https://m.media-amazon.com/images/I/41jtQIysWQL.jpg",
        price: 584.99,
        infoUrl:
          "https://pcpartpicker.com/product/qy2bt6/western-digital-gold-18-tb-35-7200rpm-internal-hard-drive-wd181kryz",
        specs: {
          "part_#": ["WD181KRYZ"],
          manufacturer: "Western Digital",
          capacity: "18 TB",
          "price/GB": "$0.032",
          type: "7200 RPM",
          caches: "512 MB",
          form_Factor: '3.5"',
          interface: "SATA 6 Gb/s",
          nVME: "No",
        },
      },
      {
        id: 55,
        name: "Western Digital Black SN850",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/67ae19fe7847cb5bf67f4448e717e831.256p.jpg",
        price: 174.99,
        infoUrl:
          "https://pcpartpicker.com/product/W69tt6/western-digital-black-sn850-1-tb-m2-2280-nvme-solid-state-drive-wds100t1x0e",
        specs: {
          "part_#": ["WDS100T1X0E"],
          manufacturer: "Western Digital",
          capacity: "1 TB",
          "price/GB": "$0.200",
          type: "SSD",
          form_Factor: "M.2-2280",
          interface: "M.2 (M)",
          nVME: "Yes",
        },
      },
      {
        id: 56,
        name: "Western Digital Black",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/dc58ee9ce6cab5a48b663ca2eee20420.256p.jpg",
        price: 149.99,
        infoUrl:
          "https://pcpartpicker.com/product/dGHRsY/western-digital-black-4tb-35-7200rpm-internal-hard-drive-wd4005fzbx",
        specs: {
          "part_#": ["WD4005FZBX"],
          manufacturer: "Western Digital",
          capacity: "4 TB",
          "price/GB": "$0.037",
          type: "7200 RPM",
          caches: "256 MB",
          form_Factor: '3.5"',
          interface: "SATA 6 Gb/s",
          nVME: "No",
        },
      },
    ],
  },
  video_card: {
    id: 6,
    title: "Video Card",
    routeName: "video_card",
    items: [
      {
        id: 57,
        name: "EVGA XC GAMING",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/151ff6807255631462c79ece5906e45f.256p.jpg",
        price: 1099.99,
        infoUrl:
          "https://pcpartpicker.com/product/LpbTwP/evga-geforce-rtx-3060-12-gb-xc-gaming-video-card-12g-p5-3657-kr",
        specs: {
          "part_#": ["12G-P5-3657-KR"],
          manufacturer: "EVGA",
          chipset: "GeForce RTX 3060",
          memory: "12 GB",
          memory_Type: "GDDR6",
          core_Clock: "1320 MHz",
          boost_Clock: "1882 MHz",
          effective_Memory_Clock: "15000 MHz",
          interface: "PCIe x16",
          frame_Sync: "G-Sync",
          length: "201.8 mm",
          tdp: "170 W",
          dVI_Ports: "0",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "3",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "2 Fans",
          external_Power: "1 PCIe 8-pin",
          displayPort: "3",
          hDMI: "1",
        },
      },
      {
        id: 58,
        name: "EVGA FTW3 ULTRA GAMING",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/6842890b8aabc12888a1b4d9c5fc7d9a.256p.jpg",
        price: 3199.0,
        infoUrl:
          "https://pcpartpicker.com/product/PG848d/evga-geforce-rtx-3090-24-gb-ftw3-ultra-gaming-video-card-24g-p5-3987-kr",
        specs: {
          "part_#": ["24G-P5-3987-KR"],
          manufacturer: "EVGA",
          chipset: "GeForce RTX 3090",
          memory: "24 GB",
          memory_Type: "GDDR6X",
          core_Clock: "1400 MHz",
          boost_Clock: "1800 MHz",
          effective_Memory_Clock: "19500 MHz",
          interface: "PCIe x16",
          "SLI/CrossFire": ["2-way SLI Capable"],
          frame_Sync: "G-Sync",
          length: "300 mm",
          tdp: "350 W",
          dVI_Ports: "0",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "3",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "3 Fans",
          external_Power: "3 PCIe 8-pin",
          displayPort: "3",
          hDMI: "1",
        },
      },
      {
        id: 59,
        name: "MSI VENTUS XS OC",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/9c57e7f04b05270bcf7edb9fcf4c715c.256p.jpg",
        price: 790.0,
        infoUrl:
          "https://pcpartpicker.com/product/Z3wkcf/msi-geforce-gtx-1660-super-6-gb-ventus-xs-oc-video-card-gtx-1660-super-ventus-xs-oc",
        specs: {
          "part_#": [
            "GTX 1660 SUPER VENTUS XS OC",
            "G166SVXSC",
            "GeForce GTX 1660 SUPER VENTUS XS OC",
            "V375-279R",
          ],
          manufacturer: "MSI",
          chipset: "GeForce GTX 1660 SUPER",
          memory: "6 GB",
          memory_Type: "GDDR6",
          core_Clock: "1530 MHz",
          boost_Clock: "1815 MHz",
          effective_Memory_Clock: "14000 MHz",
          interface: "PCIe x16",
          frame_Sync: "G-Sync",
          length: "203.962 mm",
          tdp: "125 W",
          dVI_Ports: "0",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "3",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "2 Fans",
          external_Power: "1 PCIe 8-pin",
          displayPort: "3",
          hDMI: "1",
        },
      },
      {
        id: 60,
        name: "MSI GAMING X",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/1f14312711fd98528c52385a0d9a7d5a.256p.jpg",
        price: 738.0,
        infoUrl:
          "https://pcpartpicker.com/product/YC848d/msi-geforce-gtx-1660-super-6-gb-gaming-x-video-card-gtx-1660-super-gaming-x",
        specs: {
          "part_#": [
            "GTX 1660 SUPER GAMING X",
            "GEFORCE GTX 1660 SUPER GAMING X",
            "V375-282R",
            "G166SGX",
          ],
          manufacturer: "MSI",
          chipset: "GeForce GTX 1660 SUPER",
          memory: "6 GB",
          memory_Type: "GDDR6",
          core_Clock: "1530 MHz",
          boost_Clock: "1830 MHz",
          effective_Memory_Clock: "14000 MHz",
          interface: "PCIe x16",
          frame_Sync: "G-Sync",
          length: "246.888 mm",
          tdp: "125 W",
          dVI_Ports: "0",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "3",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "2 Fans",
          external_Power: "1 PCIe 8-pin",
          displayPort: "3",
          hDMI: "1",
        },
      },
      {
        id: 61,
        name: "Zotac GAMING Twin Fan",
        imageUrl: "https://m.media-amazon.com/images/I/31UkjhcIiEL.jpg",
        price: 640.49,
        infoUrl:
          "https://pcpartpicker.com/product/y2xbt6/zotac-geforce-gtx-1660-super-6-gb-twin-fan-video-card-zt-t16620f-10l",
        specs: {
          "part_#": ["ZT-T16620F-10L"],
          manufacturer: "Zotac",
          chipset: "GeForce GTX 1660 SUPER",
          memory: "6 GB",
          memory_Type: "GDDR6",
          core_Clock: "1530 MHz",
          boost_Clock: "1785 MHz",
          effective_Memory_Clock: "14000 MHz",
          interface: "PCIe x16",
          frame_Sync: "G-Sync",
          length: "173.4 mm",
          tdp: "125 W",
          dVI_Ports: "0",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "3",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "2 Fans",
          external_Power: "1 PCIe 8-pin",
          displayPort: "3",
          hDMI: "1",
        },
      },
      {
        id: 62,
        name: "EVGA SC ULTRA GAMING",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/50af1d4d41843ea4c143fff3dfbdf33b.256p.jpg",
        price: 569.79,
        infoUrl:
          "https://pcpartpicker.com/product/LBrYcf/evga-geforce-gtx-1650-super-4-gb-sc-ultra-gaming-video-card-04g-p4-1357-kr",
        specs: {
          "part_#": ["04G-P4-1357-KR"],
          manufacturer: "EVGA",
          chipset: "GeForce GTX 1650 SUPER",
          memory: "4 GB",
          memory_Type: "GDDR6",
          core_Clock: "1530 MHz",
          boost_Clock: "1755 MHz",
          effective_Memory_Clock: "12000 MHz",
          interface: "PCIe x16",
          frame_Sync: "G-Sync",
          length: "202.1 mm",
          tdp: "100 W",
          dVI_Ports: "1",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "1",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "2 Fans",
          external_Power: "1 PCIe 8-pin",
          displayPort: "1",
          hDMI: "1",
        },
      },
      {
        id: 63,
        name: "PowerColor Red Dragon",
        imageUrl: "https://m.media-amazon.com/images/I/41fqjXZk9tL.jpg",
        price: 209.95,
        infoUrl:
          "https://pcpartpicker.com/product/CH6qqs/powercolor-radeon-rx-550-512-4-gb-red-dragon-video-card-axrx-550-4gbd5-dh",
        specs: {
          "part_#": ["AXRX 550 4GBD5-DH"],
          manufacturer: "PowerColor",
          chipset: "Radeon RX 550 - 512",
          memory: "4 GB",
          memory_Type: "GDDR5",
          core_Clock: "1100 MHz",
          boost_Clock: "1071 MHz",
          effective_Memory_Clock: "6000 MHz",
          interface: "PCIe x16",
          "sLI/CrossFire": ["2-way CrossFire Capable"],
          frame_Sync: "FreeSync",
          length: "152 mm",
          tdp: "50 W",
          dVI_Ports: "1",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "1",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "1 Fans",
          external_Power: "None",
          "dVI-D_Dual-Link": "1",
          displayPort: "1",
          hDMI: "1",
        },
      },
      {
        id: 64,
        name: "ASRock Phantom Gaming D",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/3edf9bcd4100fa82f56de5fc6c649b1b.256p.jpg",
        price: 429.88,
        infoUrl:
          "https://pcpartpicker.com/product/sWL48d/asrock-radeon-rx-570-4-tb-phantom-gaming-d-video-card-phantom-rx570-gdr-4g",
        specs: {
          "part_#": [
            "Phantom RX570 GDR 4G",
            "PHANTOM GAMING D RADEON RX570 4G",
            "PHANTOM GDR RX570 4G",
            "90-GA0K00-00UANF",
          ],
          manufacturer: "ASRock",
          chipset: "Radeon RX 570",
          memory: "4 GB",
          memory_Type: "GDDR5",
          core_Clock: "1168 MHz",
          boost_Clock: "1244 MHz",
          effective_Memory_Clock: "7000 MHz",
          interface: "PCIe x16",
          "sLI/CrossFire": [
            "2-way CrossFire Capable",
            "3-way CrossFire Capable",
            "4-way CrossFire Capable",
          ],
          frame_Sync: "FreeSync",
          length: "152 mm",
          tdp: "50 W",
          dVI_Ports: "1",
          hDMI_Ports: "1",
          "mini-HDMI_Ports": "0",
          displayPort_Ports: "1",
          "mini-DisplayPort_Ports": "0",
          expansion_Slot_Width: "2",
          cooling: "1 Fans",
          external_Power: "None",
          "dVI-D_Dual-Link": "1",
          displayPort: "1",
          hDMI: "1",
        },
      },
    ],
  },
  cases: {
    id: 7,
    title: "Case",
    routeName: "cases",
    items: [
      {
        id: 65,
        name: "NZXT H510",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/604fef5ac9874dffa927a3db98c1188d.256p.jpg",
        price: 69.98,
        infoUrl:
          "https://pcpartpicker.com/product/6Cyqqs/nzxt-h510-atx-mid-tower-case-ca-h510b-w1",
        specs: {
          "part_#": ["CA-H510B-W1"],
          manufacturer: "NZXT",
          type: "ATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 2 Type-C", "USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "7",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: [
            '381 mm/15" With Drive Cages',
            '381 mm/15" Without Drive Cages',
          ],
          dimensions: ["428mm x 210mm x 460mm", '16.85" x 8.268" x 18.11"'],
          'internal_2.5"_Bays': "2",
          'internal_3.5"_Bays': "2",
          volume: ["41.345 L", "1.46 cubic ft"],
        },
      },
      {
        id: 66,
        name: "Corsair 4000D Airflow",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/bc6e987da3fe22c616898d1d7fa3d227.256p.jpg",
        price: 94.99,
        infoUrl:
          "https://pcpartpicker.com/product/bCYQzy/corsair-4000d-airflow-atx-mid-tower-case-cc-9011200-ww",
        specs: {
          "part_#": ["CC-9011200-WW"],
          manufacturer: "Corsair",
          type: "ATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Tinted Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 2 Type-C", "USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "7",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: ['360mm/14.173"'],
          dimensions: ["453mm x 230mm x 466mm", '17.835" x 9.055" x 18.346"'],
          'internal_2.5"_Bays': "2",
          'internal_3.5"_Bays': "2",
          volume: ["48.553 L", "1.715 cubic ft"],
        },
      },
      {
        id: 67,
        name: "Corsair 275R Airflow",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/d931138ef265c1951fcd54781c390741.256p.jpg",
        price: 79.98,
        infoUrl:
          "https://pcpartpicker.com/product/sY9tt6/corsair-275r-airflow-atx-mid-tower-case-cc-9011181-ww",
        specs: {
          "part_#": ["CC-9011181-WW"],
          manufacturer: "Corsair",
          type: "ATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "7",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: ['370mm/14.567"'],
          'internal_2.5"_Bays': "4",
          'internal_3.5"_Bays': "2",
        },
      },
      {
        id: 68,
        name: "Phanteks Eclipse P300A Mesh",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/7c9e187b65ab4b281bc2ca0fe41a9aa7.256p.jpg",
        price: 59.99,
        infoUrl:
          "https://pcpartpicker.com/product/crqBD3/phanteks-eclipse-p300a-mesh-atx-mid-tower-case-ph-ec300atg_bk01",
        specs: {
          "part_#": ["PH-EC300ATG_BK01", "PH-EC300ATG_BK01_AU"],
          manufacturer: "Phanteks",
          type: "ATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "7",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: ['355mm/13.976"'],
          dimensions: ["400mm x 200mm x 455mm", '15.748" x 7.874" x 17.913"'],
          'internal_2.5"_Bays': "1",
          'internal_3.5"_Bays': "2",
          volume: ["36.4 L", "1.285 cubic ft"],
        },
      },
      {
        id: 69,
        name: "Phanteks Eclipse P400A Digital",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/b11dd409015fa37679b6a1bbcafa278f.256p.jpg",
        price: 87.0,
        infoUrl:
          "https://pcpartpicker.com/product/QdXYcf/phanteks-eclipse-p400a-digital-atx-mid-tower-case-ph-ec400atg_dbk",
        specs: {
          "part_#": ["PH-EC400ATG_DBK", "PH-EC400ATG_DBK01"],
          manufacturer: "Phanteks",
          type: "ATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "EATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "7",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: [
            '280mm/11.024" With Drive Cages',
            '420mm/16.535" Without Drive Cages',
          ],
          dimensions: ["470mm x 210mm x 465mm", '18.504" x 8.268" x 18.307"'],
          'internal_2.5"_Bays': "2",
          'internal_3.5"_Bays': "2",
          volume: ["45.895 L", "1.621 cubic ft"],
        },
      },
      {
        id: 70,
        name: "Lian Li PC-O11 Dynamic",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/580387945cfb3fe6bac9ef5844c2b55f.256p.jpg",
        price: 159.99,
        infoUrl:
          "https://pcpartpicker.com/product/VxRzK8/lian-li-pc-o11dw-atx-full-tower-case-pc-o11dw",
        specs: {
          "part_#": ["PC-O11DW", "PC011DW"],
          manufacturer: "Lian Li",
          type: "ATX Full Tower",
          power_Supply: "None",
          side_Panel_Window: "Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 2 Type-C", "USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "EATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "8",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: ['420mm/16.535" Without Drive Cages'],
          dimensions: ["445mm x 272mm x 446mm", '17.52" x 10.709" x 17.559"'],
          'internal_2.5"_Bays': "4",
          'internal_3.5"_Bays': "2",
          volume: ["53.984 L", "1.906 cubic ft"],
        },
      },
      {
        id: 71,
        name: "Fractal Design Meshify C",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/5e077c6b1272ca2c11e4f7df6326370a.256p.jpg",
        price: 97.89,
        infoUrl:
          "https://pcpartpicker.com/product/Y6Crxr/fractal-design-meshify-c-atx-mid-tower-case-fd-ca-mesh-c-bko-tg",
        specs: {
          "part_#": ["FD-CA-MESH-C-BKO-TG"],
          manufacturer: "Fractal Design",
          type: "ATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Tinted Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "7",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: ['315mm/12.402"'],
          dimensions: ["413mm x 217mm x 453mm", '16.26" x 8.543" x 17.835"'],
          'internal_2.5"_Bays': "3",
          'internal_3.5"_Bays': "2",
          volume: ["40.598 L", "1.434 cubic ft"],
        },
      },
      {
        id: 72,
        name: "Corsair iCUE 4000X RGB",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/0610d363ccccf52837f07d811e4eb2a3.256p.jpg",
        price: 134.99,
        infoUrl:
          "https://pcpartpicker.com/product/6qFKHx/corsair-icue-4000x-rgb-atx-mid-tower-case-cc-9011204-ww",
        specs: {
          "part_#": ["CC-9011204-WW"],
          manufacturer: "Corsair",
          type: "ATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Tempered Glass",
          power_Supply_Shroud: "Yes",
          front_Panel_USB: ["USB 3.2 Gen 2 Type-C", "USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["ATX", "Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "7",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: ['360mm/14.173"'],
          dimensions: ["453mm x 230mm x 466mm", '17.835" x 9.055" x 18.346"'],
          'internal_2.5"_Bays': "2",
          'internal_3.5"_Bays': "2",
          volume: ["48.553 L", "1.715 cubic ft"],
        },
      },
      {
        id: 73,
        name: "Cooler Master MasterBox Q300L",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/ec48e16ee4d6629045cfc4d71c649746.256p.jpg",
        price: 48.49,
        infoUrl:
          "https://pcpartpicker.com/product/rnGxFT/cooler-master-masterbox-q300l-microatx-mini-tower-case-mcb-q300l-kann-s00",
        specs: {
          "part_#": ["MCB-Q300L-KANN-S00"],
          manufacturer: "Cooler Master",
          type: "MicroATX Mid Tower",
          power_Supply: "None",
          side_Panel_Window: "Acrylic",
          power_Supply_Shroud: "No",
          front_Panel_USB: ["USB 3.2 Gen 1 Type-A"],
          motherboard_Form_Factor: ["Micro ATX", "Mini ITX"],
          "full-Height_Expansion_Slots": "4",
          "half-Height_Expansion_Slots": "0",
          maximum_Video_Card_Length: ['360mm/14.173"'],
          dimensions: ["387mm x 230mm x 378mm", '15.236" x 9.055" x 14.882"'],
          'internal_2.5"_Bays': "2",
          'internal_3.5"_Bays': "1",
          volume: ["33.646 L", "1.188 cubic ft"],
        },
      },
    ],
  },
  power_supply: {
    id: 8,
    title: "Power Supply",
    routeName: "power_supply",
    items: [
      {
        id: 74,
        name: "Corsair RM (2019)",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/02951377c9eed1e21fc3d8ba6092717e.256p.jpg",
        price: 124.99,
        infoUrl:
          "https://pcpartpicker.com/product/6Y66Mp/corsair-rm-2019-750-w-80-gold-certified-fully-modular-atx-power-supply-cp-9020195-na",
        specs: {
          "part_#": [
            "CP-9020195-NA",
            "CP-9020195-UK",
            "CP-9020195-AU",
            "CP-9020195-WW",
            "CP-9020195-EU",
          ],
          manufacturer: "Corsair",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Gold",
          wattage: "750 W",
          length: "160 mm",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "2",
          "pCIe_6+2-Pin_Connectors": "6",
          sATA_Connectors: "10",
          "molex_4-Pin_Connectors": "4",
        },
      },
      {
        id: 75,
        name: "EVGA BQ",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/512voawCsuL.jpg",
        price: 61.71,
        infoUrl:
          "https://pcpartpicker.com/product/DmWrxr/evga-bq-600w-80-bronze-certified-semi-modular-atx-power-supply-110-bq-0600-k1",
        specs: {
          "part_#": ["110-BQ-0600-K1", "110-BQ-0600-K2", "110-BQ-0600-K3"],
          manufacturer: "EVGA",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Bronze",
          wattage: "600 W",
          length: "140 mm",
          modular: "Semi",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "1",
          "pCIe_6+2-Pin_Connectors": "2",
          sATA_Connectors: "6",
          "molex_4-Pin_Connectors": "3",
        },
      },
      {
        id: 76,
        name: "Corsair CXM",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/097e4a536e42595ca4c7ded7f7739bd4.256p.jpg",
        price: 84.99,
        infoUrl:
          "https://pcpartpicker.com/product/R2mxFT/corsair-power-supply-cp9020103na",
        specs: {
          "part_#": ["CP-9020103-NA"],
          manufacturer: "Corsair",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Bronze",
          wattage: "650 W",
          length: "140 mm",
          modular: "Semi",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "1",
          "pCIe_6+2-Pin_Connectors": "2",
          sATA_Connectors: "6",
          "molex_4-Pin_Connectors": "4",
        },
      },
      {
        id: 77,
        name: "EVGA SuperNOVA GA",
        imageUrl: "https://m.media-amazon.com/images/I/51QtNc5IZVL.jpg",
        price: 99.98,
        infoUrl:
          "https://pcpartpicker.com/product/Xsn8TW/evga-supernova-ga-650-w-80-gold-certified-fully-modular-atx-power-supply-220-ga-0650-x1",
        specs: {
          "part_#": ["220-GA-0650-X1"],
          manufacturer: "EVGA",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Gold",
          wattage: "650 W",
          length: "150 mm",
          modular: "Full",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "1",
          "pCIe_6+2-Pin_Connectors": "6",
          sATA_Connectors: "9",
          "molex_4-Pin_Connectors": "4",
        },
      },
      {
        id: 78,
        name: "Gigabyte P GM",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/496145221d9d61487802823b7d03b98d.256p.jpg",
        price: 119.99,
        infoUrl:
          "https://pcpartpicker.com/product/RhH8TW/gigabyte-750-w-80-gold-certified-fully-modular-atx-power-supply-gp-p750gm",
        specs: {
          "part_#": ["GP-P750GM"],
          manufacturer: "Gigabyte",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Gold",
          wattage: "750 W",
          length: "140 mm",
          modular: "Full",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "2",
          "pCIe_6+2-Pin_Connectors": "4",
          sATA_Connectors: "8",
          "molex_4-Pin_Connectors": "3",
        },
      },
      {
        id: 79,
        name: "Corsair HX Platinum",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/51QvmULw-VL.jpg",
        price: 376.0,
        infoUrl:
          "https://pcpartpicker.com/product/nQJkcf/corsair-hx-platinum-1000w-80-platinum-certified-fully-modular-atx-power-supply-cp-9020139-na",
        specs: {
          "part_#": [
            "CP-9020139-NA",
            "CP-9020139-WW",
            "CP-9020139-UK",
            "CP-9020139-EU",
            "CP-9020139-AU",
            "CP-9020139-CN",
            "CP-9020139-JP",
            "CP-9020139-KR",
          ],
          manufacturer: "Corsair",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Platinum",
          wattage: "1000 W",
          length: "180 mm",
          modular: "Full",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "2",
          "pCIe_6+2-Pin_Connectors": "8",
          sATA_Connectors: "16",
          "molex_4-Pin_Connectors": "8",
          output: [
            "+3.3V@25A",
            "+5V@25A",
            "+12V@83.3A",
            "-12V@0.8A",
            "+5HXB@3A",
          ],
        },
      },
      {
        id: 80,
        name: "Corsair SF",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/41XA%2BO8OFNL.jpg",
        price: 184.99,
        infoUrl:
          "https://pcpartpicker.com/product/nJrmP6/corsair-750-w-80-platinum-certified-fully-modular-sfx-power-supply-cp-9020186-na",
        specs: {
          "part_#": [
            "CP-9020186-NA",
            "CP-9020186-EU",
            "CP-9020186-UK",
            "CP-9020186-AU",
          ],
          manufacturer: "Corsair",
          form_Factor: "SFX",
          efficiency_Rating: "80+ Platinum",
          wattage: "750 W",
          length: "100 mm",
          modular: "Full",
          type: "SFX12V",
          fanless: "No",
          ePS_Connectors: "2",
          "pCIe_6+2-Pin_Connectors": "4",
          sATA_Connectors: "8",
          "molex_4-Pin_Connectors": "3",
        },
      },
      {
        id: 81,
        name: "NZXT C",
        imageUrl:
          "https://cdna.pcpartpicker.com/static/forever/images/product/cd4625cbc62ddc42dd7818032da24d6f.256p.jpg",
        price: 129.99,
        infoUrl:
          "https://pcpartpicker.com/product/hrqBD3/nzxt-c-850-w-80-gold-certified-fully-modular-atx-power-supply-np-c850m-us",
        specs: {
          "part_#": ["NP-C850M-US", "NP-C850M-UK"],
          manufacturer: "NZXT",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Platinum",
          wattage: "850 W",
          length: "150 mm",
          modular: "Full",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "2",
          "pCIe_6+2-Pin_Connectors": "6",
          sATA_Connectors: "8",
          "molex_4-Pin_Connectors": "6",
        },
      },
      {
        id: 82,
        name: "SeaSonic FOCUS Plus Gold",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/41eNLwVUFoL.jpg",
        price: 101.67,
        infoUrl:
          "https://pcpartpicker.com/product/WrNypg/seasonic-focus-plus-gold-650w-80-gold-certified-fully-modular-atx-power-supply-ssr-650fx",
        specs: {
          "part_#": ["SSR-650FX"],
          manufacturer: "SeaSonic",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Gold",
          wattage: "650 W",
          length: "140 mm",
          modular: "Full",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "1",
          "pCIe_6+2-Pin_Connectors": "4",
          sATA_Connectors: "8",
          "molex_4-Pin_Connectors": "3",
          output: ["+3.3V@20A", "+5V@20A", "+12V@54A", "-12V@0.3A", "+5Vsb@3A"],
        },
      },
      {
        id: 83,
        name: "Corsair TXM Gold",
        imageUrl:
          "https://images-na.ssl-images-amazon.com/images/I/41QTtqXKzqL.jpg",
        price: 109.98,
        infoUrl:
          "https://pcpartpicker.com/product/PVzZxr/corsair-txm-gold-650w-80-gold-certified-semi-modular-atx-power-supply-cp-9020132-na",
        specs: {
          "part_#": ["CP-9020132-NA", "CP-9020132-UK"],
          manufacturer: "Corsair",
          form_Factor: "ATX",
          efficiency_Rating: "80+ Gold",
          wattage: "650 W",
          length: "140 mm",
          modular: "Semi",
          type: "ATX",
          fanless: "No",
          ePS_Connectors: "1",
          "pCIe_6+2-Pin_Connectors": "4",
          sATA_Connectors: "6",
          "molex_4-Pin_Connectors": "4",
          output: [
            "+3.3V@25A",
            "+5V@25A",
            "+12V@51A",
            "-12V@0.8A",
            "+5TX-MB@3A",
          ],
        },
      },
    ],
  },
};

export default SHOP_DATA;
